name: Create Release

on:
  workflow_run:
    workflows: ['Run Checks']
    types:
      - completed

jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Extract Package Version
        id: extract_version
        run: |
          PACKAGE_VERSION=$(node -p "require('./package.json').version")
          DATE_TAG=$(date +"%Y%m%d%H%M")
          echo "RELEASE_TAG=${PACKAGE_VERSION}-${DATE_TAG}" >> $GITHUB_OUTPUT

      - name: Create Draft Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.extract_version.outputs.RELEASE_TAG }}
          name: Release v${{ steps.extract_version.outputs.RELEASE_TAG }}
          draft: true

      - name: Tag as Latest
        run: |
          git tag -f latest
          git push origin latest --force

      - name: Stop depending actions if errors
        if: failure()
        run: exit 1
