name: Run Checks

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Prettier Check
        run: npm run format:check

      - name: Linter Check
        run: npm run lint:check

      - name: Type Check
        run: npm run build:check

      - name: Tests and Coverage Check
        run: npm run coverage --coverageThreshold="{\"global\":{\"branches\":100,\"functions\":100,\"lines\":100,\"statements\":100}}"

      - name: Stop depending actions if errors
        if: failure()
        run: exit 1
